# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: PIG æ„å»ºaction

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'
          cache: maven

      - name: mvn spring-javaformat:validate
        run: mvn spring-javaformat:validate

      - name: mvn clean install
        run: mvn clean install

      - name: Start containers
        run: docker-compose build && docker-compose up -d

      - name:  failure
        if: failure() && github.repository == 'pig-mesh/pig'
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: |
            # ğŸ’¤ğŸ¤·â€â™€ï¸ failure ğŸ™…â€â™‚ï¸ğŸ’£ [pig-mesh/pig](https://github.com/pig-mesh/pig)
            > Github Action: https://github.com/pig-mesh/pig failure
            > (â‹Ÿï¹â‹)   from github action message


  # ä¾èµ–å‡çº§å®Œæˆåï¼Œè‡ªåŠ¨åˆå¹¶PR
  # https://docs.github.com/zh/enterprise-cloud@latest/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
  dependabot:
    name: Dependabot
    # éœ€è¦æ‰€æœ‰ build å®Œæˆåï¼Œæ‰è¿è¡Œ
    needs: build
    runs-on: ${{ matrix.os }}
    permissions:
      # å¯ä»¥ä¿®æ”¹ä»“åº“ä¸­çš„æ–‡ä»¶å†…å®¹
      contents: write
      # # å¯ä»¥æ–°å»ºæˆ–ä¿®æ”¹ Pull Request
      pull-requests: write
    # ä¾èµ–æœºå™¨äºº && ä»…PR
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}

    strategy:
      matrix:
        os: [ "ubuntu-latest" ]

    steps:

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: echo
        run: |
          echo ${{ github.event.pull_request.html_url }}
          echo ${{ steps.metadata.outputs.dependency-names }}
          echo ${{ steps.metadata.outputs.update-type }}
          echo ${{ 'version-update:semver-patch' }}

      - name: Enable auto-merge for Dependabot PRs
        # if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
